name: Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  ssh-trigger-deploy:
    environment:
      name: "Main"
      url: "https://sora-reader.app"
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to ssh server
        uses: appleboy/ssh-action@v0.1.4
        with:
          debug: true
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script : |
            . $HOME/.profile
            cd "$DEPLOYMENT_DIR"
            make deploy frontend

