name: EC2 deploy

on:
  workflow_run:
    workflows: [ "Continuous integration" ]
    branches: [ master ]
    types:
      - "completed"

jobs:
  Deploy-application:
    environment:
      name: "AWS-T2-WS"
      url: "https://sora-reader.app"
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to ssh server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script : |
            cd ${{ secrets.SOURCE_PATH }}
            git fetch origin master || exit 1
            git reset --hard origin/master || exit 1

            docker build \
              -m 4g \
              --build-arg NODE_OPTIONS=--max_old_space_size=3700 \
              --build-arg SENTRY_DSN=${{ secrets.SENTRY_DSN }} \
              --build-arg SENTRY_URL=${{ secrets.SENTRY_URL }} \
              --build-arg SENTRY_ORG=${{ secrets.SENTRY_ORG }} \
              --build-arg SENTRY_PROJECT=${{ secrets.SENTRY_PROJECT }} \
              --build-arg SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }} \
              -t "sora-frontend:$(git rev-parse HEAD)" .
            [ $? = "0" ] || exit $?
            
            docker stop sora-frontend
            docker rm sora-frontend

            docker run -d --restart unless-stopped --network host \
              --name sora-frontend --env-file=${{ secrets.SOURCE_PATH }}/.env \
              "sora-frontend:$(git rev-parse HEAD)"
            [ $? = "0" ] || exit $?

            sleep 1
            docker image prune -f -a
            exit
